AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'omnibus/bin/*'

Layout/LineLength:
  Max: 80

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/LineEndConcatenation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
    '%i': '{}'
    '%I': '{}'
    '%w': '{}'
    '%W': '{}'
    '%r': '{}'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Metrics/PerceivedComplexity:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
