AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/LineEndConcatenation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
    '%i': '{}'
    '%I': '{}'
    '%w': '{}'
    '%W': '{}'
    '%r': '{}'
