on_push: [lint]
lint:
  - name: rubocop
    command: scripts/run_rubocop.sh -D -a
  - name: mdl
    command: scripts/run_mdl.sh -g .
  - name: shellcheck
    command: shellcheck $(find . -name \*.sh -o -name \*.bash)
unit:
  - name: rspec
    command: scripts/run_rspec.sh
