driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 2048
  synced_folders:
    - ['..', '/home/vagrant/sugarjar']

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
    run_list: yum-epel::default
  - name: centos-stream-8
    run_list: yum-epel::default
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: debian-11
    run_list: apt::default
  - name: fedora-31
    run_list: yum-fedora::default
  - name: ubuntu-18.04
    run_list: apt::default
  - name: ubuntu-20.04
    run_list: apt::default
  - name: ubuntu-22.04
    run_list: apt::default

suites:
  - name: default
    run_list: omnibus::default
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/sugarjar
