# This is a sample `repoconfig` for SugarJar
#
# Configs should be named `.sugarjar.yaml` and placed in the root
# of your repository.
#

# `include_from` is a meta config wich will read from an additional
# configuration file and merge anything from the file onto whatever is in the
# primary file. This is helpful to have a repo configuration that applies to
# all/most developers, but allow individual developers to add to over overwrite
# specific configurations for themselves. If the file does not exist, this
# configuration is ignored.

include_from: .sugarjar_local.yaml

# `overwrite_from` is a meta config which works much like `include_from`,
# except that if the file is found, everything else in this configuration file
# will be ignored and the configuration will be entirely read from the
# referenced file.  If the file does not exist, this configuration is ignored.

overwrite_from: .sugarjar_local_overwrite.yaml

# `primary_branch` allows you to configure a primary branch that is
# non-standard. If your primary branch is `main` or `master`, you do not need
# to set this, sugarjar will figure out out automatically.
#
# This can also be used to force a primary branch in the event you have
# both `main` and `master` around.
primary_branch: somethingweird

# `release_branches` tells SugarJar several things:
#   1. These branches should not be repead when running `bclean`/`bcleanall`.
#   2. When a feature-branch is made from a release branch (e.g. `2.x-branch`),
#      it will actually track the release branch's upstream
#      (e.g. `upstream/2.x-bramch`), allowing it to work the same as as a
#      feature made off of main.
release_branches:
  - 2.x-branch
  - 3.x-branch

# `lint` is a list of scripts to run when `sj lint` is executed (or, if
# configured, to run on `sj spush`/`sj fpush` - see `on_push` below).
# Regardless of where `sj` is run from, these scripts will be run from the root
# of the repo. If a slash is detected in the first 'word' of the command, it
# is assumed it is a relative path and `sj` will check that the file exists.

lint:
  # can be a string which is just a command to run...
  - scripts/run_rubocop.sh
  # want it to have a pretty name? Entries can be a hash instead...
  - name: mdl
    command: scripts/run_mdl.sh

# `unit` is a list of scripts to run when `sj unit` is executed (or, if
# configured to run on `sj spush`/`sj fpush`- see `on_push` below).  Regardless
# of where `sj` is run from, these scripts will be run from the root of the
# repo. If a slash is detected in the first 'word' of the command, it is
# assumed it is a relative path and `sj` will check that the file exists.

unit:
  # like lint, supports bare strings...
  - bundle exec rspec
  # or hashes...
  - name: unittests
    command: scripts/run_tests.sh

# `lint_list_cmd` is like `lint`, except it's a command to run which will
# determine the proper lints to run and return them, one per line. This is
# useful, for example, when you want to only run lints relevant to the changed
# files.

lint_list_cmd: scripts/determine_linters.sh

# `unit_list_cmd` is like `unit`, except it's a command to run which will
# determine the proper units to run and return them, one per line. This is
# useful, for example, when you want to only run tests relevant to the changed
# files.

unit_list_cmd: scripts/determine_tests.sh

# `on_push` determines what checks should be run when pushing a repo. Valid
# options are `lint` and/or `unit` (or nothing, of course).

on_push: [lint] # or [lint, unit]

# `commit_template` points to a file to set the git `commit.template` config
# to. This is really useful for ensuring that everyone has the same
# template configured.

commit_template: .git_commit_template.txt
