Vagrant.configure('2') do |config|
  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--memory', 2048]
    v.name = 'f36'
  end
  config.vm.box = 'fedora/36-cloud-base'
  config.vm.provision :shell, :path => 'provision.sh'
  config.vm.synced_folder '..', '/home/vagrant/sugarjar'
  config.vm.synced_folder '../../pastel', '/home/vagrant/pastel'
  config.vm.synced_folder '../../tty-color', '/home/vagrant/tty-color'
  config.ssh.insert_key = false
end
