Vagrant.configure('2') do |config|
  # Libvirt/KVM VM (Fedora 41)
  config.vm.define 'f41' do |f41|
    f41.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 2
    end
    f41.vm.box = 'fedora/41-cloud-base'
    f41.vm.provision :shell, :path => 'provision.sh'
    f41.vm.synced_folder '..', '/home/vagrant/sugarjar',
                         :type => 'nfs', :nfs_version => 4
    f41.vm.synced_folder '../../pastel', '/home/vagrant/pastel',
                         :type => 'nfs', :nfs_version => 4
    f41.vm.synced_folder '../../tty-color', '/home/vagrant/tty-color',
                         :type => 'nfs', :nfs_version => 4
    f41.ssh.insert_key = false
  end
end
