Vagrant.configure('2') do |config|
  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--memory', 2048]
  end
  config.vm.box = 'fedora/33-cloud-base'
  config.vm.provision :shell, :path => 'provision.sh'
  config.vm.synced_folder '..', '/home/vagrant/sugarjar'
end
