name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  rspec:
    permissions:
      contents: read
      pull-requests: read
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3, 3.4, 4.0]
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - name: Install system dependencies
      run: |-
        sudo apt update
        sudo apt install -y gh glab
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install Ruby dependencies
      run: bundle install
    - name: Run rspec
      run: ./scripts/run_rspec.sh
    - name: Run specs outside of repo
      run: |-
        cd ..
        bundle exec --gemfile=sugarjar/Gemfile rspec sugarjar/spec
